/* eslint-disable no-unused-vars */
export const CREATE_ORDER_PENDING = "CREATE_ORDER_PENDING";
export const CREATE_ORDER_FULFILLED = "CREATE_ORDER_FULFILLED";
export const CREATE_ORDER_REJECTED = "CREATE_ORDER_REJECTED";

export const GET_ORDER_FULFILLED = "GET_ORDER_FULFILLED";
export const GET_ORDER_PENDING = "GET_ORDER_PENDING";
export const GET_ORDER_REJECTED = "GET_ORDER_REJECTED";
