/* eslint-disable no-unused-vars */
export const CREATE_ORDER_PENDING = "CREATE_ORDER_PENDING";
export const CREATE_ORDER_FULFILLED = "CREATE_ORDER_FULFILLED";
export const CREATE_ORDER_REJECTED = "CREATE_ORDER_REJECTED";

export const GET_ORDERR_FULFILLED = "GET_ORDERR_FULFILLED";
export const GET_ORDERR_PENDING = "GET_ORDERR_PENDING";
export const GET_ORDERR_REJECTED = "GET_ORDERR_REJECTED";

export const GET_SELLER_ORDER_FULFILLED = "GET_SELLER_ORDER_FULFILLED";
export const GET_SELLER_ORDER_PENDING = "GET_SELLER_ORDER_PENDING";
export const GET_SELLER_ORDER_REJECTED = "GET_SELLER_ORDER_REJECTED";

export const APROOVE_ORDER_FULFILLED = "APROOVE_ORDER_FULFILLED";
export const APROOVE_ORDER_PENDING = "APROOVE_ORDER_PENDING";
export const APROOVE_ORDER_REJECTED = "APROOVE_ORDER_REJECTED";
