export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_FULFILLED = "REGISTER_FULFILLED";
export const REGISTER_REJECTED = "REGISTER_REJECTED";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const GETUSER_PENDING = "GETUSER_PENDING";
export const GETUSER_FULFILLED = "GETUSER_FULFILLED";
export const GETUSER_REJECTED = "GETUSER_REJECTED";

export const LOGOUT = "LOGOUT";
